# Generated by Django 4.0.6 on 2022-07-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('unseen', 'Unseen'), ('recntly_seen', 'Recently seen'), ('ad_in_cart', 'Add in cart')], default='unseen', max_length=40),
        ),
    ]
