# Generated by Django 4.0.6 on 2022-07-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_options_product_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='format',
            field=models.CharField(choices=[('choose_the_format', 'Choose the format'), ('cd', 'CD'), ('lp', 'LP'), ('digital', 'Digital'), ('casette', 'Casette')], default='choose_the_format', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='song_list',
            field=models.TextField(default='Not Mentioned'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
